import { SpekLayoutConfig, ScoreLayoutConfig } from '../../types';

export interface LayoutPreset<T> {
  id: string;
  name: string;
  badge: string;
  description: string;
  icon: string;
  config: Partial<T>;
}

export const SPEK_PRESETS: LayoutPreset<SpekLayoutConfig>[] = [
  {
    id: 'modern_bento_glass',
    name: 'Modern Glass Bento',
    badge: 'Populer',
    description: 'Tata letak bento grid asimetris modern dengan efek frost glass transparan',
    icon: '🌟',
    config: {
      layout: 'bento_grid',
      visualStyle: 'glassmorphism',
      spacing: 3,
      cardBackground: 'glass_transparent',
      showIcons: true,
      showCategoryHeaders: true,
      showCountBadges: true,
      showHelpButtons: true,
      attributesColor: '#00E5FF',
      appealColor: '#F59E0B',
      specialtyColor: '#10B981',
    },
  },
  {
    id: 'cyberpunk_neon_hud',
    name: 'Cyberpunk Neon HUD',
    badge: 'Futuristik',
    description: 'Matrix HUD cyberpunk dengan glowing neon chips bergaris tajam',
    icon: '⚡',
    config: {
      layout: 'matrix_hud',
      visualStyle: 'glowing_chips',
      spacing: 2,
      cardBackground: 'neon_bordered',
      showIcons: true,
      showCategoryHeaders: true,
      showCountBadges: true,
      showHelpButtons: true,
      attributesColor: '#00F0FF',
      appealColor: '#FFD000',
      specialtyColor: '#00FF66',
    },
  },
  {
    id: 'swiss_clean_dots',
    name: 'Swiss Minimalist Clean',
    badge: 'Minimalis',
    description: '3 Kolom simetris berorientasi teks bersih dengan bullet dots teratur',
    icon: '🎯',
    config: {
      layout: 'three_columns',
      visualStyle: 'compact_dots',
      spacing: 2,
      cardBackground: 'subtle_dark',
      showIcons: false,
      showCategoryHeaders: true,
      showCountBadges: false,
      showHelpButtons: false,
      attributesColor: '#94A3B8',
      appealColor: '#CBD5E1',
      specialtyColor: '#E2E8F0',
    },
  },
  {
    id: 'soft_pill_cloud',
    name: 'Soft Pill Fluid Cloud',
    badge: 'Organik',
    description: 'Tag cloud mengalir bebas dengan pil kapsul lembut berpendar',
    icon: '🏷️',
    config: {
      layout: 'tag_cloud',
      visualStyle: 'pill_tags',
      spacing: 3,
      cardBackground: 'subtle_dark',
      showIcons: true,
      showCategoryHeaders: true,
      showCountBadges: true,
      showHelpButtons: true,
      attributesColor: '#38BDF8',
      appealColor: '#FB923C',
      specialtyColor: '#34D399',
    },
  },
  {
    id: 'tabbed_focus_pro',
    name: 'Tabbed Focus Pro',
    badge: 'Hemat Ruang',
    description: 'Navigasi tab per kategori untuk menghemat ruang vertikal layar',
    icon: '📑',
    config: {
      layout: 'tabbed_categories',
      visualStyle: 'bordered_cards',
      spacing: 2,
      cardBackground: 'solid_elevated',
      showIcons: true,
      showCategoryHeaders: false,
      showCountBadges: true,
      showHelpButtons: true,
      attributesColor: '#06B6D4',
      appealColor: '#F59E0B',
      specialtyColor: '#10B981',
    },
  },
  {
    id: 'developer_terminal_cli',
    name: 'Developer Terminal CLI',
    badge: 'Monospace',
    description: 'Gaya console developer dengan baris berkode monospace dan border kaku',
    icon: '💻',
    config: {
      layout: 'single_column',
      visualStyle: 'terminal_cli',
      spacing: 1,
      cardBackground: 'solid_elevated',
      showIcons: false,
      showCategoryHeaders: true,
      showCountBadges: true,
      showHelpButtons: true,
      attributesColor: '#4ADE80',
      appealColor: '#FACC15',
      specialtyColor: '#2DD4BF',
    },
  },
  {
    id: 'royal_gradient_accent',
    name: 'Royal Gradient Outline',
    badge: 'Mewah',
    description: 'Tata letak 2 kolom elegan bergaris aksen gradasi berpendar mewah',
    icon: '👑',
    config: {
      layout: 'two_columns',
      visualStyle: 'gradient_outline',
      spacing: 4,
      cardBackground: 'subtle_dark',
      showIcons: true,
      showCategoryHeaders: true,
      showCountBadges: true,
      showHelpButtons: true,
      attributesColor: '#F59E0B',
      appealColor: '#EC4899',
      specialtyColor: '#8B5CF6',
    },
  },
];

export const SCORE_PRESETS: LayoutPreset<ScoreLayoutConfig>[] = [
  {
    id: 'pro_analytical_studio',
    name: 'Pro Studio Analytical',
    badge: 'Standar Pro',
    description: '2 Kolom seimbang dengan progress bars presisi desimal 1 angka & bobot lengkap',
    icon: '📊',
    config: {
      layout: 'two_columns',
      visualStyle: 'progress_bars',
      colorScheme: 'neon_cyan_pink',
      showWeightBadges: true,
      showPercentFillBar: true,
      showHelpButtons: true,
      showScoreScale: true,
      numberPrecision: 'decimal_1',
      spacing: 3,
      headerStyle: 'modern_banner',
      appearanceColor: '#06B6D4',
      impressionColor: '#EC4899',
      overallColor: '#F59E0B',
    },
  },
  {
    id: 'radial_chrono_gauge',
    name: 'Radial Speedometer Chrono',
    badge: 'Dial Radial',
    description: 'Split master rating dengan circular gauges melingkar seperti speedometer',
    icon: '⏱️',
    config: {
      layout: 'split_master',
      visualStyle: 'circular_gauges',
      colorScheme: 'amber_gold',
      showWeightBadges: true,
      showPercentFillBar: true,
      showHelpButtons: true,
      showScoreScale: false,
      numberPrecision: 'integer',
      spacing: 3,
      headerStyle: 'badge_prominent',
      appearanceColor: '#F59E0B',
      impressionColor: '#EAB308',
      overallColor: '#F97316',
    },
  },
  {
    id: 'cyber_equalizer_spectrum',
    name: 'Cyber Equalizer Spectrum',
    badge: 'Spektrum',
    description: 'Grid padat dengan bar equalizer audio spektrum neon vertikal menyala',
    icon: '🎛️',
    config: {
      layout: 'compact_matrix',
      visualStyle: 'equalizer_bars',
      colorScheme: 'violet_magenta',
      showWeightBadges: false,
      showPercentFillBar: true,
      showHelpButtons: true,
      showScoreScale: true,
      numberPrecision: 'integer',
      spacing: 2,
      headerStyle: 'hud_header',
      appearanceColor: '#8B5CF6',
      impressionColor: '#D946EF',
      overallColor: '#A855F7',
    },
  },
  {
    id: 'swiss_minimalist_mono',
    name: 'Swiss Minimalist Typography',
    badge: 'Ultra Bersih',
    description: 'Baris bertumpuk elegan dengan tipografi angka bersih dan microbars halus',
    icon: '💎',
    config: {
      layout: 'stacked_rows',
      visualStyle: 'minimal_numbers',
      colorScheme: 'monochrome_slate',
      showWeightBadges: true,
      showPercentFillBar: true,
      showHelpButtons: false,
      showScoreScale: false,
      numberPrecision: 'decimal_1',
      spacing: 2,
      headerStyle: 'simple_clean',
      appearanceColor: '#94A3B8',
      impressionColor: '#CBD5E1',
      overallColor: '#E2E8F0',
    },
  },
  {
    id: 'arcade_retro_gaming',
    name: 'Arcade Retro Gaming',
    badge: 'Neon Retro',
    description: 'HUD dashboard gaming dengan bilah arcade neon retro menyala bersemangat',
    icon: '🎮',
    config: {
      layout: 'hud_dashboard',
      visualStyle: 'arcade_neon',
      colorScheme: 'emerald_teal',
      showWeightBadges: true,
      showPercentFillBar: true,
      showHelpButtons: true,
      showScoreScale: true,
      numberPrecision: 'integer',
      spacing: 3,
      headerStyle: 'hud_header',
      appearanceColor: '#10B981',
      impressionColor: '#14B8A6',
      overallColor: '#059669',
    },
  },
  {
    id: 'tabbed_master_cards',
    name: 'Tabbed Master Cards',
    badge: 'Kartu Metrik',
    description: 'Tab interaktif Appearance vs Impression dengan kartu metrik angka besar',
    icon: '📑',
    config: {
      layout: 'tabbed_panels',
      visualStyle: 'score_cards',
      colorScheme: 'neon_cyan_pink',
      showWeightBadges: true,
      showPercentFillBar: true,
      showHelpButtons: true,
      showScoreScale: true,
      numberPrecision: 'decimal_1',
      spacing: 3,
      headerStyle: 'modern_banner',
      appearanceColor: '#06B6D4',
      impressionColor: '#EC4899',
      overallColor: '#F59E0B',
    },
  },
  {
    id: 'bento_hex_matrix',
    name: 'Bento Hex Matrix Tech',
    badge: 'Cyber Tech',
    description: 'Bento box asimetris dengan matriks segmen digital presisi tinggi',
    icon: '🔬',
    config: {
      layout: 'bento_scores',
      visualStyle: 'radar_matrix',
      colorScheme: 'neon_cyan_pink',
      showWeightBadges: true,
      showPercentFillBar: true,
      showHelpButtons: true,
      showScoreScale: true,
      numberPrecision: 'decimal_1',
      spacing: 3,
      headerStyle: 'hud_header',
      appearanceColor: '#06B6D4',
      impressionColor: '#F43F5E',
      overallColor: '#EAB308',
    },
  },
];
