import { Artist } from '../types';
import {
  calculateAppearanceScore,
  calculateImpressionScore,
  calculateOverallRating,
  calculateProportionalRating,
  calculateAge,
  getCountryFlag,
  getTypeInfo,
  getScoreStatus,
} from './calculations';

/**
 * Generates a clean, formatted text profile summary of an artist
 * optimized for sharing via Messaging, Clipboard, Telegram, Discord, or Markdown.
 */
export function generateArtistTextSummary(artist: Artist): string {
  const app = calculateAppearanceScore(artist.appearanceScores);
  const imp = calculateImpressionScore(artist.impressionScores);
  const overall = calculateOverallRating(app, imp);
  const prop = calculateProportionalRating(artist.measurements);
  const age = calculateAge(artist.bornDate);
  const flag = getCountryFlag(artist.countryCode, artist.country);
  const typeInfo = getTypeInfo(artist.typeCode);
  const scoreStatus = getScoreStatus(overall);
  const fullName = `${artist.firstName} ${artist.lastName || ''}`.trim();
  const isSpecial = (artist.attributes?.length || 0) > 0;
  const status = (artist.artistStatus || (isSpecial ? 'Special' : 'Standard')).toUpperCase();

  const lines = [
    `✨ PROFIL PENILAIAN ARTIS: ${fullName} [${status}]`,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    `🌍 Negara: ${flag} ${artist.country} (${artist.countryCode})`,
    `🎂 Usia: ${age > 0 ? `${age} Tahun` : '-'} | 🗓️ Lahir: ${artist.bornDate || '-'} | 🎬 Debut: ${artist.debutDate || '-'}`,
    `🧍 Tipe Tubuh: ${artist.typeCode} (${typeInfo?.indonesia || '-'})`,
    `📐 Tinggi: ${artist.heightCm || '-'} cm`,
    `👙 Ukuran: B ${artist.measurements?.bustCm || '-'} / W ${artist.measurements?.waistCm || '-'} / H ${artist.measurements?.hipCm || '-'} (Cup ${artist.measurements?.cupSize || '-'})`,
    `⚖️ Nilai Proporsional BWH: ${prop}/99`,
    ``,
    `⭐ OVERALL RATING: ${overall}/99 [${scoreStatus.label} • ${scoreStatus.tier}]`,
    `├── 🌸 Appearance Score (60%): ${app.toFixed(1)}/99`,
    `│   ├── Wajah (25%): ${artist.appearanceScores?.face || 0}`,
    `│   ├── Kulit (15%): ${artist.appearanceScores?.skin || 0}`,
    `│   ├── Payudara (15%): ${artist.appearanceScores?.breast || 0}`,
    `│   ├── Bokong (15%): ${artist.appearanceScores?.butt || 0}`,
    `│   ├── V (10%): ${artist.appearanceScores?.v || 0}`,
    `│   └── Paha & Betis (20%): ${artist.appearanceScores?.thighCalve || 0}`,
    `└── 🎭 Impression Score (40%): ${imp.toFixed(1)}/99`,
    `    ├── Suara (15%): ${artist.impressionScores?.voice || 0}`,
    `    ├── Ekspresi (20%): ${artist.impressionScores?.expression || 0}`,
    `    ├── Sex Appeal (20%): ${artist.impressionScores?.sexAppeal || 0}`,
    `    ├── Keaslian (15%): ${artist.impressionScores?.authenticity || 0}`,
    `    ├── Chemistry (15%): ${artist.impressionScores?.chemistry || 0}`,
    `    └── Aura (15%): ${artist.impressionScores?.aura || 0}`,
    ``,
    `🧬 APPEAL TAXONOMY:`,
    `• Maturity: ${artist.appeal?.maturity || '-'}`,
    `• Vibe: ${artist.appeal?.vibe || '-'}`,
    `• Style: ${artist.appeal?.style || '-'}`,
    `• Body Shape: ${artist.appeal?.bodyShape || '-'}`,
  ];

  if (artist.attributes && artist.attributes.length > 0) {
    lines.push(`✨ Atribut Khusus: ${artist.attributes.join(', ')}`);
  }

  if (artist.specialty && artist.specialty.length > 0) {
    lines.push(`🎯 Spesialisasi: ${artist.specialty.join(', ')}`);
  }

  if (artist.links && artist.links.length > 0) {
    lines.push(``);
    lines.push(`🔗 TAUTAN EKSTERNAL:`);
    artist.links.forEach(link => {
      lines.push(`• ${link.name}: ${link.url}`);
    });
  }

  if (artist.notes) {
    lines.push(``);
    lines.push(`📝 Catatan Tambahan: ${artist.notes}`);
  }

  lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`Generated by IDOL PRO 5 - Database & Scoring System`);

  return lines.join('\n');
}

/**
 * Copies text safely to clipboard with fallback for non-secure contexts
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const successful = document.execCommand('copy');
      document.body.removeChild(textArea);
      return successful;
    }
  } catch (err) {
    console.error('Failed to copy text:', err);
    return false;
  }
}
